GET http://localhost:3000/users/allusers

###
GET http://localhost:3000/users/user_detail/61373af1358fd8e3e732934b

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "firstName" : "Piyush",
    "lastName" : "Kadam",
    "email" : "pk@123mail.com",
    "password" : "12345"
}

###
DELETE http://localhost:3000/users/delete/613610e8e5c56d7042e26668

###
PATCH http://localhost:3000/users/update/6137bcc44b4633d2074170af
Content-Type: application/json

{
    # "firstName" : "Piyush",
    # "lastName" : "Kadam",
    # "email" : "pk@123mail.com",
    "password" : 12345
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "ak@123mail.com",
    "password" : 45678
}

###
GET http://localhost:3000/notes/allnotes

###
GET http://localhost:3000/notes/6137a9d85692eb7deb83a1c2

###
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title" : "Title - 3",
    "description" : "Desciption - 3",
    "color" : "#c1429b"
}

###
PATCH http://localhost:3000/notes/update/613827e2ce3b51fde8105c6f
Content-Type: application/json

{
    "title" : "Title - 4",
    "description" : "Description - 4",
    "color" : "#ffffff"
}

###
PATCH http://localhost:3000/notes/delete/613827e2ce3b51fde8105c6f
# Content-Type: application/json

# {
#     "isDeleted" : true
# }

###
PATCH http://localhost:3000/notes/archive/613827e2ce3b51fde8105c6f
# Content-Type: application/json

# {
#     "isArchived" : true
# }