GET http://localhost:3000/users/allusers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE

###
GET http://localhost:3000/users/user_detail/61373af1358fd8e3e732934b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "firstName" : "Smit",
    "lastName" : "Koli",
    "email" : "piyushdk74@gmail.com",
    "password" : "678910"
}

###
DELETE http://localhost:3000/users/delete/61382b682e3084ab69eead31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE

###
PATCH http://localhost:3000/users/update/613f6cce76e59b3116e8e17f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE
Content-Type: application/json

{
    # "firstName" : "Piyush",
    # "lastName" : "Kadam",
    # "email" : "pika7138@gmail.com",
     "password" : "12345"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "pika7138@gmail.com",
    "password" : 12345
}

###
POST http://localhost:3000/users/forget/614027b836b8563f1ec46cad
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE
Content-Type: application/json

{
    "email" : "pika7138@gmail.com"
}

###
PATCH http://localhost:3000/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNjEzNTU1fQ.-vcGkA4P8zk_0N5oa4eYF-w_km68iYgK1n1rfjmbprY
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNjEzNTU1fQ.-vcGkA4P8zk_0N5oa4eYF-w_km68iYgK1n1rfjmbprY  
Content-Type: application/json

{
    "password" : "91011"
}

###
GET http://localhost:3000/notes/allnotes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE

###
GET http://localhost:3000/notes/note/6137a9d85692eb7deb83a1c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE

###
POST http://localhost:3000/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE
Content-Type: application/json

{
    "title" : "Title - 4",
    "description" : "Desciption - 4",
    "color" : "#c1429b"
}

###
PATCH http://localhost:3000/notes/update/613827e2ce3b51fde8105c6f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE
Content-Type: application/json

{
    "title" : "Title - 3",
    "description" : "Description - 3",
    "color" : "#ffffff"
}

###
PATCH http://localhost:3000/notes/delete/6140531575de5368ab565400
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE
Content-Type: application/json

{
    "isDeleted" : true
}

###
PATCH http://localhost:3000/notes/archive/6140520bb0498f956f27e325
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE
Content-Type: application/json

{
    "isArchived" : true
}

###
DELETE http://localhost:3000/notes/deletenote/613f1f20de334c962a02e6cd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNTMwNTUzfQ.4lFFzJuNSRMkx24oAbckF3jtXyDavgS-9aa-km-ZdcE

###
GET http://localhost:3000/notes/alldeletednotes 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNjEzNTU1fQ.-vcGkA4P8zk_0N5oa4eYF-w_km68iYgK1n1rfjmbprY

###
GET http://localhost:3000/notes/allarchivednotes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE0MDI3YjgzNmI4NTYzZjFlYzQ2Y2FkIiwiaWF0IjoxNjMxNjEzNTU1fQ.-vcGkA4P8zk_0N5oa4eYF-w_km68iYgK1n1rfjmbprY
